# Generated by Django 4.2.7 on 2023-12-11 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webrestaurant', '0005_infobooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_checkout', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('busy', 'Busy')], max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='account',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Account',
        ),
        migrations.CreateModel(
            name='DetailBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webrestaurant.bill')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webrestaurant.product')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webrestaurant.account'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webrestaurant.table'),
        ),
    ]
