# Generated by Django 4.2.7 on 2023-12-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurant', '0006_bill_table_rename_customer_order_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_checkout',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_price',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
