# Generated by Django 4.2.7 on 2023-12-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurant', '0007_alter_bill_date_checkout_alter_bill_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_checkout',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10),
        ),
    ]
