# Generated by Django 4.2.7 on 2023-12-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurant', '0009_remove_bill_id_table_bill_id_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
