# Generated by Django 4.2.7 on 2023-12-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurant', '0010_category_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
