# Generated by Django 4.2.7 on 2023-12-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurant', '0011_alter_bill_date_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_checkout',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
