# Generated by Django 4.2.7 on 2023-12-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurant', '0014_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer')], default='ADMIN', max_length=20),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
