# Generated by Django 4.2.7 on 2023-12-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurant', '0017_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infobooking',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('WAIT', 'Wait'), ('CANCEL', 'Cancel')], default='WAIT', max_length=20),
        ),
    ]
