# Generated by Django 4.2.7 on 2023-12-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurant', '0019_remove_infobooking_user_infobooking_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infobooking',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webrestaurant.account'),
        ),
    ]
