# Generated by Django 4.2.7 on 2023-12-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurant', '0021_alter_infobooking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('empty', 'Empty'), ('busy', 'Busy')], default='empty', max_length=10),
        ),
    ]
