# Generated by Django 4.2.7 on 2024-01-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrestaurant', '0022_alter_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobooking',
            name='paytype',
            field=models.CharField(choices=[('COD', 'Thanh toán tại nhà hàng'), ('PAYONLINE', 'Thanh toán online')], default='COD', max_length=20),
        ),
    ]
